services:
  db:
    image: mongo
    container_name: web3tickets_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: web3tickets_backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://db:27017/web3tickets
    depends_on:
      - db

  # blockchain:
  #   build: ./blockchain
  #   container_name: web3tickets_blockchain
  #   ports:
  #     - "8545:8545"

  frontend:
    build: ./frontend
    container_name: web3tickets_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=http://localhost:4000/graphql
      - NEXT_PUBLIC_LOCAL_CHAIN_ID=31337
    depends_on:
      - backend
      - blockchain

volumes:
  mongodb_data:
