services:
  db:
    image: mongo:6
    container_name: web3tickets_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: web3tickets
    ports:
      - "27017:27017"
    volumes:
      - ./backend/db_data:/data/db # Ruta de volumen de Mongo

  backend:
    build: ./backend
    container_name: web3tickets_backend
    restart: always
    env_file:
      - ./backend/.env # Aseg√∫rate que este archivo tenga el MONGODB_URI
    ports:
      - "4000:4000"
    depends_on:
      - db # CAMBIADO: Ahora depende del servicio 'db' (que es mongo)
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: web3tickets_frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
